version: '3.4'

## docker run --name myadmin --link db --network h -p 8081:80 phpmyadmin/phpmyadmin

services: 
  
  wordpress: 
    image: ${IMAGE}:${BUILD_NUMBER}
    restart: always
    networks: 
      - wordpress
    command: apachectl -D FOREGROUND  
    volumes: 
      - ./source:/var/www/html
      - ./init/server/php.ini-development:/usr/local/etc/php/php.ini
    ports: 
      - 85:80
    external_links:
      - 'dbwp-maxspeed'  
    environment:
      - MYSQL_ROOT_PASSWORD=123456789
   
  db_maxpseed:
    container_name: dbwp-maxspeed
    command: --default-authentication-plugin=mysql_native_password
    image: mysql:8.0
    restart: always
    volumes:
      - ./init/db/:/docker-entrypoint-initdb.d/
    ports:
      - 3309:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456789
    networks: 
      - wordpress

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks: 
      - wordpress

networks:
  wordpress:
    external: false 